2021-01-08 16:44:35,957 - Main - DEBUG - Starting
2021-01-08 16:44:38,468 - Application - DEBUG - The following input was received, starting event process: 1234
2021-01-08 16:44:38,469 - ScanEvent - DEBUG - Constructor was called
2021-01-08 16:44:38,469 - ScanEvent - DEBUG - The following Hash was scanned: 1234
2021-01-08 16:44:38,469 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-08 16:44:38,469 - Database - DEBUG - Constructor was called
2021-01-08 16:44:38,485 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-08 16:44:38,485 - ScanEvent - DEBUG - QR is valid
2021-01-08 16:44:38,486 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 1234
2021-01-08 16:44:38,486 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=1234;
2021-01-08 16:44:38,487 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (1234)
2021-01-08 16:44:38,496 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-08 16:44:38,496 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-08 16:44:38,496 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-08 16:44:38,498 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-08 16:44:38,498 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-08 16:44:38,501 - ScanEvent - DEBUG - Received the following entries: ()
2021-01-08 16:44:38,501 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbegin
2021-01-08 16:44:38,501 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6001,)
2021-01-08 16:44:38,590 - Application - DEBUG - Wiping all information from screen
2021-01-10 10:28:08,861 - Main - DEBUG - Starting
2021-01-10 10:28:18,549 - Main - DEBUG - Starting
2021-01-10 10:29:28,886 - Main - DEBUG - Starting
2021-01-10 10:30:38,519 - Main - DEBUG - Starting
2021-01-10 11:39:07,432 - Main - DEBUG - Starting
2021-01-10 11:39:25,500 - Main - DEBUG - Starting
2021-01-12 11:20:34,160 - Main - DEBUG - Starting
2021-01-12 11:20:36,431 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 11:20:36,431 - ScanEvent - DEBUG - Constructor was called
2021-01-12 11:20:36,431 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 11:20:36,431 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 11:20:36,431 - Database - DEBUG - Constructor was called
2021-01-12 11:20:36,531 - Database - ERROR - The following error occured in constructor of database: (1045, "Access denied for user 'terminal'@'ip-88-152-34-6.hsi03.unitymediagroup.de' (using password: YES)")
2021-01-12 11:20:36,531 - ScanEvent - ERROR - The following error occured in the constructor such that DatabaseDisconnect exception will be raised: 
2021-01-12 11:20:36,531 - Application - WARNING - Displaying that no connectivity but values will be stored
2021-01-12 11:20:36,531 - Application - DEBUG - Wiping all information from screen
2021-01-12 11:21:59,007 - Main - DEBUG - Starting
2021-01-12 11:22:01,218 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 11:22:01,218 - ScanEvent - DEBUG - Constructor was called
2021-01-12 11:22:01,218 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 11:22:01,218 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 11:22:01,218 - Database - DEBUG - Constructor was called
2021-01-12 11:22:01,316 - Database - ERROR - The following error occured in constructor of database: (1045, "Access denied for user 'terminal'@'ip-88-152-34-6.hsi03.unitymediagroup.de' (using password: YES)")
2021-01-12 11:22:01,317 - ScanEvent - ERROR - The following error occured in the constructor such that DatabaseDisconnect exception will be raised: 
2021-01-12 11:22:01,317 - Application - WARNING - Displaying that no connectivity but values will be stored
2021-01-12 11:22:01,317 - Application - DEBUG - Wiping all information from screen
2021-01-12 19:57:29,718 - Main - DEBUG - Starting
2021-01-12 19:57:32,035 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 19:57:32,035 - ScanEvent - DEBUG - Constructor was called
2021-01-12 19:57:32,035 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 19:57:32,035 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 19:57:32,035 - Database - DEBUG - Constructor was called
2021-01-12 19:57:32,186 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 19:57:32,300 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 19:57:32,300 - ScanEvent - DEBUG - QR is valid
2021-01-12 19:57:32,301 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 19:57:32,302 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 19:57:32,303 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 19:57:32,325 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 19:57:32,325 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 19:57:32,325 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 19:57:32,365 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 19:57:32,365 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 19:57:32,389 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 19:57:32,389 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 19:57:32,389 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6001,)
2021-01-12 19:57:32,456 - Application - DEBUG - Wiping all information from screen
2021-01-12 19:57:39,586 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 19:57:39,586 - ScanEvent - DEBUG - Constructor was called
2021-01-12 19:57:39,586 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 19:57:39,587 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 19:57:39,587 - Database - DEBUG - Constructor was called
2021-01-12 19:57:39,741 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 19:57:39,890 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 19:57:39,890 - ScanEvent - DEBUG - QR is valid
2021-01-12 19:57:39,891 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 19:57:39,892 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 19:57:39,910 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 19:57:39,919 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 19:57:39,919 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 19:57:39,919 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 19:57:39,957 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 19:57:39,958 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 19:57:39,977 - ScanEvent - DEBUG - Received the following entries: [(108, 6001, datetime.datetime(2021, 1, 12, 19, 57, 32), None, 'Normal', datetime.datetime(2021, 1, 12, 19, 57, 32), 0)]
2021-01-12 19:57:39,977 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-12 19:57:39,977 - ScanEvent - DEBUG - Found shift start at: 2021-01-12 19:57:32
2021-01-12 19:57:39,977 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6001 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-12 19:57:40,038 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-12 19:57:40,039 - ScanEvent - DEBUG - Shift sum is 00 hours and 00 minutes
2021-01-12 19:57:40,043 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:27,464 - Main - DEBUG - Starting
2021-01-12 20:02:29,721 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:02:29,721 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:29,721 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:02:29,721 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:29,721 - Database - DEBUG - Constructor was called
2021-01-12 20:02:29,922 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:30,043 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:30,043 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:02:30,044 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:02:30,044 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:02:30,044 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:02:30,087 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:02:30,087 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:02:30,087 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:02:30,120 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:02:30,120 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:02:30,156 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:02:30,157 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:02:30,157 - Application - ERROR - The following error occured in enter input: 'App' object has no attribute 'textMain'
2021-01-12 20:02:30,158 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:36,512 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:02:36,512 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:36,512 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:02:36,512 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:36,512 - Database - DEBUG - Constructor was called
2021-01-12 20:02:36,671 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:36,794 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:36,794 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:02:36,795 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:02:36,795 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:02:36,801 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:02:36,833 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:02:36,833 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:02:36,834 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:02:36,863 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:02:36,863 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:02:36,886 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:02:36,886 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:02:36,886 - Application - ERROR - The following error occured in enter input: 'App' object has no attribute 'textMain'
2021-01-12 20:02:36,886 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:41,065 - Application - DEBUG - The following input was received, starting event process: 
2021-01-12 20:02:41,066 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:41,066 - ScanEvent - DEBUG - The following Hash was scanned: 
2021-01-12 20:02:41,066 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:41,066 - Database - DEBUG - Constructor was called
2021-01-12 20:02:41,258 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:41,386 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:41,386 - ScanEvent - WARNING - The QR is not a valid QR Code
2021-01-12 20:02:41,387 - Application - DEBUG - Displaying that QR is not valid
2021-01-12 20:02:41,396 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:41,743 - Application - DEBUG - The following input was received, starting event process: 
2021-01-12 20:02:41,744 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:41,744 - ScanEvent - DEBUG - The following Hash was scanned: 
2021-01-12 20:02:41,744 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:41,744 - Database - DEBUG - Constructor was called
2021-01-12 20:02:41,941 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:42,042 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:42,042 - ScanEvent - WARNING - The QR is not a valid QR Code
2021-01-12 20:02:42,042 - Application - DEBUG - Displaying that QR is not valid
2021-01-12 20:02:42,042 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:45,145 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:02:45,145 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:45,145 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:02:45,145 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:45,145 - Database - DEBUG - Constructor was called
2021-01-12 20:02:45,299 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:45,425 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:45,425 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:02:45,426 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:02:45,426 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:02:45,433 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:02:45,453 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:02:45,453 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:02:45,453 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:02:45,479 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:02:45,479 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:02:45,495 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:02:45,495 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:02:45,495 - Application - ERROR - The following error occured in enter input: 'App' object has no attribute 'textMain'
2021-01-12 20:02:45,495 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:48,992 - Application - DEBUG - The following input was received, starting event process: 
2021-01-12 20:02:48,992 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:48,992 - ScanEvent - DEBUG - The following Hash was scanned: 
2021-01-12 20:02:48,992 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:48,992 - Database - DEBUG - Constructor was called
2021-01-12 20:02:49,156 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:49,279 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:49,279 - ScanEvent - WARNING - The QR is not a valid QR Code
2021-01-12 20:02:49,279 - Application - DEBUG - Displaying that QR is not valid
2021-01-12 20:02:49,280 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:02:55,689 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:02:55,689 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:02:55,689 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:02:55,690 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:02:55,690 - Database - DEBUG - Constructor was called
2021-01-12 20:02:55,863 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:02:56,008 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:02:56,009 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:02:56,009 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:02:56,009 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:02:56,015 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:02:56,072 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:02:56,072 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:02:56,072 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:02:56,095 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:02:56,096 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:02:56,119 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:02:56,119 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:02:56,119 - Application - ERROR - The following error occured in enter input: 'App' object has no attribute 'textMain'
2021-01-12 20:02:56,119 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:04:23,089 - Main - DEBUG - Starting
2021-01-12 20:04:25,560 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:04:25,560 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:04:25,560 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:04:25,560 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:04:25,560 - Database - DEBUG - Constructor was called
2021-01-12 20:04:25,725 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:04:25,849 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:04:25,849 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:04:25,850 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:04:25,850 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:04:25,851 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:04:25,888 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:04:25,888 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:04:25,888 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:04:25,921 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:04:25,922 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:04:25,952 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:04:25,952 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:04:25,952 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6001,)
2021-01-12 20:04:25,996 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:04:29,905 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:04:29,905 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:04:29,905 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:04:29,905 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:04:29,905 - Database - DEBUG - Constructor was called
2021-01-12 20:04:30,063 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:04:30,182 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:04:30,182 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:04:30,183 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:04:30,183 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:04:30,193 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:04:30,209 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:04:30,209 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:04:30,209 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:04:30,230 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-12 20:04:30,230 - Application - DEBUG - Displaying that code was already scanned
2021-01-12 20:04:30,230 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:04:34,952 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:04:34,953 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:04:34,953 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:04:34,953 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:04:34,953 - Database - DEBUG - Constructor was called
2021-01-12 20:04:35,108 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:04:35,220 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:04:35,220 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:04:35,221 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:04:35,221 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:04:35,230 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:04:35,262 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:04:35,262 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:04:35,262 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:04:35,287 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:04:35,288 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:04:35,312 - ScanEvent - DEBUG - Received the following entries: [(109, 6001, datetime.datetime(2021, 1, 12, 20, 4, 26), None, 'Normal', datetime.datetime(2021, 1, 12, 20, 4, 26), 0)]
2021-01-12 20:04:35,312 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-12 20:04:35,312 - ScanEvent - DEBUG - Found shift start at: 2021-01-12 20:04:26
2021-01-12 20:04:35,312 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6001 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-12 20:04:35,368 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-12 20:04:35,368 - ScanEvent - DEBUG - Shift sum is 00 hours and 00 minutes
2021-01-12 20:04:35,368 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:06:35,349 - Main - DEBUG - Starting
2021-01-12 20:06:37,785 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:06:37,785 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:06:37,786 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:06:37,786 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:06:37,786 - Database - DEBUG - Constructor was called
2021-01-12 20:06:37,954 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:06:38,070 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:06:38,071 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:06:38,071 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:06:38,072 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:06:38,072 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:06:38,113 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:06:38,113 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:06:38,113 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:06:38,133 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:06:38,133 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:06:38,158 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:06:38,159 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:06:38,159 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6001,)
2021-01-12 20:06:38,194 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:06:40,859 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:06:40,859 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:06:40,859 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:06:40,859 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:06:40,859 - Database - DEBUG - Constructor was called
2021-01-12 20:06:41,016 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:06:41,129 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:06:41,129 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:06:41,130 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:06:41,130 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:06:41,137 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:06:41,161 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:06:41,161 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:06:41,161 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:06:41,185 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-12 20:06:41,186 - Application - DEBUG - Displaying that code was already scanned
2021-01-12 20:06:41,186 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:07:40,468 - Main - DEBUG - Starting
2021-01-12 20:07:43,128 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-12 20:07:43,128 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:07:43,129 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-12 20:07:43,129 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:07:43,129 - Database - DEBUG - Constructor was called
2021-01-12 20:07:43,266 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:07:43,390 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:07:43,391 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:07:43,391 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-12 20:07:43,392 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345678;
2021-01-12 20:07:43,392 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345678)
2021-01-12 20:07:43,415 - ScanEvent - DEBUG - Person is known, received the following identity: (6001, 'Murat', 'Bayram')
2021-01-12 20:07:43,416 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6001, Murat, Bayram
2021-01-12 20:07:43,416 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6001 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:07:43,439 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:07:43,440 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6001 and Dienstende is NULL
2021-01-12 20:07:43,457 - ScanEvent - DEBUG - Received the following entries: [(110, 6001, datetime.datetime(2021, 1, 12, 20, 6, 38), None, 'Normal', datetime.datetime(2021, 1, 12, 20, 6, 38), 0)]
2021-01-12 20:07:43,457 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-12 20:07:43,458 - ScanEvent - DEBUG - Found shift start at: 2021-01-12 20:06:38
2021-01-12 20:07:43,458 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6001 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-12 20:07:43,504 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-12 20:07:43,504 - ScanEvent - DEBUG - Shift sum is 00 hours and 01 minutes
2021-01-12 20:07:43,505 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:07:47,504 - Application - DEBUG - The following input was received, starting event process: 12345674
2021-01-12 20:07:47,504 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:07:47,504 - ScanEvent - DEBUG - The following Hash was scanned: 12345674
2021-01-12 20:07:47,504 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:07:47,504 - Database - DEBUG - Constructor was called
2021-01-12 20:07:47,651 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:07:47,756 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:07:47,756 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:07:47,757 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345674
2021-01-12 20:07:47,757 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=12345674;
2021-01-12 20:07:47,764 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (12345674)
2021-01-12 20:07:47,788 - ScanEvent - WARNING - Person is unknown
2021-01-12 20:07:47,788 - Application - DEBUG - Displaying Person is unknown
2021-01-12 20:07:47,788 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:11:04,848 - Main - DEBUG - Starting
2021-01-12 20:16:09,083 - Main - DEBUG - Starting
2021-01-12 20:16:12,967 - Application - DEBUG - The following input was received, starting event process: ztrzetrz
2021-01-12 20:16:12,967 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:16:12,967 - ScanEvent - DEBUG - The following Hash was scanned: ztrzetrz
2021-01-12 20:16:12,967 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:16:12,967 - Database - DEBUG - Constructor was called
2021-01-12 20:16:13,177 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:16:13,409 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:16:13,410 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:16:13,411 - Failover in local DB - DEBUG - Creating local copy of data from following hash: ztrzetrz
2021-01-12 20:16:13,411 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash=ztrzetrz;
2021-01-12 20:16:13,412 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (ztrzetrz)
2021-01-12 20:16:13,414 - Failover in local DB - ERROR - The following error occured in create backup event, rolling back: no such column: ztrzetrz
2021-01-12 20:16:13,481 - Database - ERROR - The following error occured in read all: 1054 (42S22): Unknown column 'ztrzetrz' in 'where clause'
2021-01-12 20:16:13,481 - Application - ERROR - The following error occured in enter input: 
2021-01-12 20:16:13,481 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:17:11,311 - Main - DEBUG - Starting
2021-01-12 20:17:15,766 - Application - DEBUG - The following input was received, starting event process: asdfghjk
2021-01-12 20:17:15,766 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:17:15,766 - ScanEvent - DEBUG - The following Hash was scanned: asdfghjk
2021-01-12 20:17:15,766 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:17:15,766 - Database - DEBUG - Constructor was called
2021-01-12 20:17:15,911 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:17:16,046 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:17:16,046 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:17:16,048 - Failover in local DB - DEBUG - Creating local copy of data from following hash: asdfghjk
2021-01-12 20:17:16,048 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='asdfghjk';
2021-01-12 20:17:16,049 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values (asdfghjk)
2021-01-12 20:17:16,050 - Failover in local DB - ERROR - The following error occured in create backup event, rolling back: no such column: asdfghjk
2021-01-12 20:17:16,072 - ScanEvent - WARNING - Person is unknown
2021-01-12 20:17:16,072 - Application - DEBUG - Displaying Person is unknown
2021-01-12 20:17:16,073 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:18:20,809 - Main - DEBUG - Starting
2021-01-12 20:18:24,222 - Application - DEBUG - The following input was received, starting event process: hghghghg
2021-01-12 20:18:24,222 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:18:24,222 - ScanEvent - DEBUG - The following Hash was scanned: hghghghg
2021-01-12 20:18:24,222 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:18:24,222 - Database - DEBUG - Constructor was called
2021-01-12 20:18:24,386 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:18:24,496 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:18:24,496 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:18:24,496 - Failover in local DB - DEBUG - Creating local copy of data from following hash: hghghghg
2021-01-12 20:18:24,496 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='hghghghg';
2021-01-12 20:18:24,497 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('hghghghg')
2021-01-12 20:18:24,518 - ScanEvent - WARNING - Person is unknown
2021-01-12 20:18:24,518 - Application - DEBUG - Displaying Person is unknown
2021-01-12 20:18:24,519 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:19:16,368 - Main - DEBUG - Starting
2021-01-12 20:20:20,296 - Application - DEBUG - The following input was received, starting event process: kGNVKHgj
2021-01-12 20:20:20,296 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:20:20,296 - ScanEvent - DEBUG - The following Hash was scanned: kGNVKHgj
2021-01-12 20:20:20,296 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:20:20,296 - Database - DEBUG - Constructor was called
2021-01-12 20:20:20,420 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:20:20,571 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:20:20,572 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:20:20,573 - Failover in local DB - DEBUG - Creating local copy of data from following hash: kGNVKHgj
2021-01-12 20:20:20,574 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='kGNVKHgj';
2021-01-12 20:20:20,575 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('kGNVKHgj')
2021-01-12 20:20:20,597 - ScanEvent - DEBUG - Person is known, received the following identity: (6002, 'Max', 'Mustermann')
2021-01-12 20:20:20,598 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6002, Max, Mustermann
2021-01-12 20:20:20,598 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6002 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:20:20,626 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:20:20,626 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6002 and Dienstende is NULL
2021-01-12 20:20:20,648 - ScanEvent - DEBUG - Received the following entries: []
2021-01-12 20:20:20,649 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-12 20:20:20,649 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6002,)
2021-01-12 20:20:20,699 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:20:25,051 - Application - DEBUG - The following input was received, starting event process: kGNVKHgj
2021-01-12 20:20:25,052 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:20:25,052 - ScanEvent - DEBUG - The following Hash was scanned: kGNVKHgj
2021-01-12 20:20:25,052 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:20:25,052 - Database - DEBUG - Constructor was called
2021-01-12 20:20:25,180 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:20:25,311 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:20:25,311 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:20:25,312 - Failover in local DB - DEBUG - Creating local copy of data from following hash: kGNVKHgj
2021-01-12 20:20:25,312 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='kGNVKHgj';
2021-01-12 20:20:25,318 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('kGNVKHgj')
2021-01-12 20:20:25,332 - ScanEvent - DEBUG - Person is known, received the following identity: (6002, 'Max', 'Mustermann')
2021-01-12 20:20:25,332 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6002, Max, Mustermann
2021-01-12 20:20:25,332 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6002 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:20:25,366 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-12 20:20:25,366 - Application - DEBUG - Displaying that code was already scanned
2021-01-12 20:20:25,366 - Application - DEBUG - Wiping all information from screen
2021-01-12 20:20:28,190 - Application - DEBUG - The following input was received, starting event process: kGNVKHgj
2021-01-12 20:20:28,190 - ScanEvent - DEBUG - Constructor was called
2021-01-12 20:20:28,190 - ScanEvent - DEBUG - The following Hash was scanned: kGNVKHgj
2021-01-12 20:20:28,190 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-12 20:20:28,190 - Database - DEBUG - Constructor was called
2021-01-12 20:20:28,408 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-12 20:20:28,522 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-12 20:20:28,523 - ScanEvent - DEBUG - QR is valid
2021-01-12 20:20:28,524 - Failover in local DB - DEBUG - Creating local copy of data from following hash: kGNVKHgj
2021-01-12 20:20:28,524 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='kGNVKHgj';
2021-01-12 20:20:28,534 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('kGNVKHgj')
2021-01-12 20:20:28,551 - ScanEvent - DEBUG - Person is known, received the following identity: (6002, 'Max', 'Mustermann')
2021-01-12 20:20:28,551 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6002, Max, Mustermann
2021-01-12 20:20:28,552 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6002 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-12 20:20:28,591 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-12 20:20:28,591 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6002 and Dienstende is NULL
2021-01-12 20:20:28,619 - ScanEvent - DEBUG - Received the following entries: [(112, 6002, datetime.datetime(2021, 1, 12, 20, 20, 21), None, 'Normal', datetime.datetime(2021, 1, 12, 20, 20, 21), 0)]
2021-01-12 20:20:28,620 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-12 20:20:28,620 - ScanEvent - DEBUG - Found shift start at: 2021-01-12 20:20:21
2021-01-12 20:20:28,620 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6002 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-12 20:20:28,664 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-12 20:20:28,665 - ScanEvent - DEBUG - Shift sum is 00 hours and 00 minutes
2021-01-12 20:20:28,666 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:50:32,986 - Main - DEBUG - Starting
2021-01-14 08:50:51,400 - Main - DEBUG - Starting
2021-01-14 08:50:53,615 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:50:53,615 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:50:53,615 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:50:53,615 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:50:53,615 - Database - DEBUG - Constructor was called
2021-01-14 08:50:53,683 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:50:53,780 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:50:53,781 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:50:53,782 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:50:53,782 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:50:53,783 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:50:53,961 - ScanEvent - WARNING - Person is unknown
2021-01-14 08:50:53,961 - Application - DEBUG - Displaying Person is unknown
2021-01-14 08:50:53,962 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:50:56,337 - Application - DEBUG - The following input was received, starting event process: 1234
2021-01-14 08:50:56,337 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:50:56,337 - ScanEvent - DEBUG - The following Hash was scanned: 1234
2021-01-14 08:50:56,337 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:50:56,337 - Database - DEBUG - Constructor was called
2021-01-14 08:50:56,343 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:50:56,354 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:50:56,354 - ScanEvent - WARNING - The QR is not a valid QR Code
2021-01-14 08:50:56,354 - Application - DEBUG - Displaying that QR is not valid
2021-01-14 08:50:56,357 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:51:54,379 - Main - DEBUG - Starting
2021-01-14 08:51:56,847 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:51:56,847 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:51:56,847 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:51:56,847 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:51:56,847 - Database - DEBUG - Constructor was called
2021-01-14 08:51:56,847 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:51:56,863 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:51:56,863 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:51:56,863 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:51:56,863 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:51:56,863 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:51:56,869 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:51:56,869 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:51:56,869 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-14 08:51:56,875 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-14 08:51:56,875 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6701 and Dienstende is NULL
2021-01-14 08:51:56,877 - ScanEvent - DEBUG - Received the following entries: []
2021-01-14 08:51:56,877 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-14 08:51:56,877 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6701,)
2021-01-14 08:51:56,939 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:52:08,164 - Main - DEBUG - Starting
2021-01-14 08:53:17,670 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:53:17,670 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:53:17,670 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:53:17,670 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:53:17,670 - Database - DEBUG - Constructor was called
2021-01-14 08:53:17,686 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:53:17,686 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:53:17,686 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:53:17,686 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:53:17,686 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:53:17,701 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:53:17,704 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:53:17,704 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:53:17,704 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-14 08:53:17,710 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-14 08:53:17,710 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6701 and Dienstende is NULL
2021-01-14 08:53:17,711 - ScanEvent - DEBUG - Received the following entries: [(5003, 6701, datetime.datetime(2021, 1, 14, 8, 51, 56), None, 'Normal', datetime.datetime(2021, 1, 14, 8, 51, 56), 0)]
2021-01-14 08:53:17,711 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-14 08:53:17,711 - ScanEvent - DEBUG - Found shift start at: 2021-01-14 08:51:56
2021-01-14 08:53:17,711 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6701 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-14 08:53:17,786 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-14 08:53:17,786 - ScanEvent - DEBUG - Shift sum is 00 hours and 01 minutes
2021-01-14 08:53:17,786 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:54:13,153 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:54:13,154 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:54:13,154 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:54:13,154 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:54:13,154 - Database - DEBUG - Constructor was called
2021-01-14 08:54:13,159 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:54:13,167 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:54:13,167 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:54:13,168 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:54:13,168 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:54:13,169 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:54:13,169 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:54:13,169 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-14 08:54:13,174 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:54:13,175 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-14 08:54:13,175 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6701 and Dienstende is NULL
2021-01-14 08:54:13,179 - ScanEvent - DEBUG - Received the following entries: []
2021-01-14 08:54:13,180 - ScanEvent - DEBUG - No other entries found, seems to be Dienstbeginn
2021-01-14 08:54:13,180 - ScanEvent - DEBUG - Opening shift, using the following query and tupel: Insert into Dienste (Personalnummer) VALUES ('%s'), (6701,)
2021-01-14 08:54:13,279 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:54:41,545 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:54:41,545 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:54:41,545 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:54:41,545 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:54:41,545 - Database - DEBUG - Constructor was called
2021-01-14 08:54:41,550 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:54:41,557 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:54:41,557 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:54:41,558 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:54:41,558 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:54:41,560 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:54:41,560 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:54:41,560 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5 SECOND);
2021-01-14 08:54:41,565 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:54:41,566 - ScanEvent - DEBUG - Code was not scanned within the last 5 seconds
2021-01-14 08:54:41,566 - ScanEvent - DEBUG - Checking whether there are open entries, using the following query: Select * from Dienste where Personalnummer=6701 and Dienstende is NULL
2021-01-14 08:54:41,571 - ScanEvent - DEBUG - Received the following entries: [(5004, 6701, datetime.datetime(2021, 1, 14, 8, 54, 12), None, 'Normal', datetime.datetime(2021, 1, 14, 8, 54, 12), 0)]
2021-01-14 08:54:41,571 - ScanEvent - DEBUG - One entry found, seems to be Dienstende
2021-01-14 08:54:41,571 - ScanEvent - DEBUG - Found shift start at: 2021-01-14 08:54:12
2021-01-14 08:54:41,571 - ScanEvent - DEBUG - Closing shift, using the following query: Update Dienste SET Dienstende = current_timestamp(), AutoClosed = '0' WHERE Personalnummer = 6701 and Dienstende is NULL ORDER BY Dienstbeginn DESC LIMIT 1
2021-01-14 08:54:41,593 - ScanEvent - DEBUG - Calculating sum of the shift
2021-01-14 08:54:41,593 - ScanEvent - DEBUG - Shift sum is 00 hours and 00 minutes
2021-01-14 08:54:41,593 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:55:09,304 - Main - DEBUG - Starting
2021-01-14 08:55:11,880 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:55:11,880 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:55:11,880 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:55:11,880 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:55:11,880 - Database - DEBUG - Constructor was called
2021-01-14 08:55:11,888 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:55:11,896 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:55:11,896 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:55:11,896 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:55:11,896 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:55:11,896 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:55:11,898 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:55:11,898 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:55:11,898 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5000 SECOND);
2021-01-14 08:55:11,904 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-14 08:55:11,904 - Application - DEBUG - Displaying that code was already scanned
2021-01-14 08:55:11,904 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:55:32,217 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:55:32,218 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:55:32,218 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:55:32,218 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:55:32,218 - Database - DEBUG - Constructor was called
2021-01-14 08:55:32,224 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:55:32,231 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:55:32,231 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:55:32,232 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:55:32,232 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:55:32,234 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:55:32,234 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:55:32,234 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5000 SECOND);
2021-01-14 08:55:32,239 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:55:32,244 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-14 08:55:32,244 - Application - DEBUG - Displaying that code was already scanned
2021-01-14 08:55:32,244 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:56:08,176 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 08:56:08,176 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:56:08,176 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 08:56:08,176 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:56:08,176 - Database - DEBUG - Constructor was called
2021-01-14 08:56:08,192 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:56:08,198 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345678
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345678';
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - Person is known, received the following identity: (6701, 'asperiores', 'voluptatem')
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - Found the following Personalnummer, Vorname, Name in the identity: 6701, asperiores, voluptatem
2021-01-14 08:56:08,198 - ScanEvent - DEBUG - Checking if same code was scanned the last 5 secondsusing the following query: Select * from Dienste where Personalnummer=6701 and Updated > (NOW() - INTERVAL 5000 SECOND);
2021-01-14 08:56:08,198 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345678')
2021-01-14 08:56:08,216 - ScanEvent - WARNING - Code was scanned in the last 5 seconds, dropping scan event.
2021-01-14 08:56:08,216 - Application - DEBUG - Displaying that code was already scanned
2021-01-14 08:56:08,216 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:57:11,521 - Application - DEBUG - The following input was received, starting event process: 12345677
2021-01-14 08:57:11,522 - ScanEvent - DEBUG - Constructor was called
2021-01-14 08:57:11,522 - ScanEvent - DEBUG - The following Hash was scanned: 12345677
2021-01-14 08:57:11,522 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 08:57:11,522 - Database - DEBUG - Constructor was called
2021-01-14 08:57:11,528 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 08:57:11,536 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 08:57:11,536 - ScanEvent - DEBUG - QR is valid
2021-01-14 08:57:11,536 - Failover in local DB - DEBUG - Creating local copy of data from following hash: 12345677
2021-01-14 08:57:11,536 - ScanEvent - DEBUG - Getting the Personalnummer and names, using the following query: Select Personalnummer, Vorname, Nachname from Personal where Hash='12345677';
2021-01-14 08:57:11,539 - ScanEvent - WARNING - Person is unknown
2021-01-14 08:57:11,539 - Application - DEBUG - Displaying Person is unknown
2021-01-14 08:57:11,539 - Application - DEBUG - Wiping all information from screen
2021-01-14 08:57:11,543 - Failover in local DB - DEBUG - Wiriting to database using the following query: INSERT INTO Dienste ("Hash") Values ('12345677')
2021-01-14 09:19:21,322 - Application - DEBUG - The following input was received, starting event process: 124
2021-01-14 09:19:21,322 - ScanEvent - DEBUG - Constructor was called
2021-01-14 09:19:21,322 - ScanEvent - DEBUG - The following Hash was scanned: 124
2021-01-14 09:19:21,322 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 09:19:21,322 - Database - DEBUG - Constructor was called
2021-01-14 09:19:21,338 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 09:19:21,338 - ScanEvent - DEBUG - Checking if QR is valid
2021-01-14 09:19:21,338 - ScanEvent - WARNING - The QR is not a valid QR Code
2021-01-14 09:19:21,338 - Application - DEBUG - Displaying that QR is not valid
2021-01-14 09:19:21,338 - Application - DEBUG - Wiping all information from screen
2021-01-14 09:22:55,467 - Main - DEBUG - Starting
2021-01-14 09:23:08,315 - Application - DEBUG - The following input was received, starting event process: 12345678
2021-01-14 09:23:08,315 - ScanEvent - DEBUG - Constructor was called
2021-01-14 09:23:08,315 - ScanEvent - DEBUG - The following Hash was scanned: 12345678
2021-01-14 09:23:08,315 - ScanEvent - DEBUG - Starting Databaseconnect
2021-01-14 09:23:08,315 - Database - DEBUG - Constructor was called
2021-01-14 09:23:08,331 - mysql.connector.connection - DEBUG - new_auth_plugin: mysql_native_password
2021-01-14 09:23:08,409 - Database - ERROR - The following error occured in constructor of database: 1045 (28000): Access denied for user 'root123'@'172.17.0.1' (using password: YES)
2021-01-14 09:23:08,409 - ScanEvent - ERROR - The following error occured in the constructor such that DatabaseDisconnect exception will be raised: 
2021-01-14 09:23:08,409 - Application - WARNING - Displaying that no connectivity but values will be stored
2021-01-14 09:23:08,409 - Application - DEBUG - Wiping all information from screen
